import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useLocation,useNavigate} from 'react-router-dom';
import axios from 'axios';
import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const api=axios.create({baseURL:API});
api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
function App(){
 const nav=useNavigate(), location=useLocation();
 const [user,setUser]=useState(JSON.parse(localStorage.getItem('user')||'null'));
 const [products,setProducts]=useState([]),[cart,setCart]=useState(JSON.parse(localStorage.getItem('cart')||'[]'));
 const [q,setQ]=useState(''),[cat,setCat]=useState('All'),[sort,setSort]=useState('newest');
 const [authOpen,setAuthOpen]=useState(false),[mode,setMode]=useState('login'),[loading,setLoading]=useState(false),[orders,setOrders]=useState([]),[coupon,setCoupon]=useState(''),[couponApplied,setCouponApplied]=useState(false);
 useEffect(()=>{api.get('/products',{params:{q,category:cat==='All'?'':cat,sort}}).then(r=>setProducts(r.data)).catch(()=>{})},[q,cat,sort]);
 useEffect(()=>localStorage.setItem('cart',JSON.stringify(cart)),[cart]);
 const cats=useMemo(()=>['All',...new Set(products.map(p=>p.category))],[products]);
 const subtotal=cart.reduce((s,i)=>s+i.price*i.quantity,0),discount=couponApplied?subtotal*.1:0,shipping=subtotal-discount>=999?0:(cart.length?79:0),total=subtotal-discount+shipping;
 const add=p=>setCart(c=>{const f=c.find(i=>i.product===p._id);return f?c.map(i=>i.product===p._id?{...i,quantity:i.quantity+1}:i):[...c,{product:p._id,title:p.title,price:p.price,image:p.images?.[0],quantity:1}]});
 async function authSubmit(e){e.preventDefault();setLoading(true);try{const r=await api.post(`/auth/${mode}`,Object.fromEntries(new FormData(e.currentTarget)));localStorage.setItem('token',r.data.token);localStorage.setItem('user',JSON.stringify(r.data.user));setUser(r.data.user);setAuthOpen(false)}catch(x){alert(x.response?.data?.message||'Something went wrong')}finally{setLoading(false)}}
 async function loadOrders(){if(!user)return;try{setOrders((await api.get('/orders')).data)}catch{}}
 async function checkout(e){e.preventDefault();if(!user)return setAuthOpen(true);const f=new FormData(e.currentTarget);const shippingAddress={fullName:f.get('fullName'),phone:f.get('phone'),addressLine:f.get('addressLine'),city:f.get('city'),state:f.get('state'),pincode:f.get('pincode')};try{const r=await api.post('/orders',{items:cart.map(i=>({product:i.product,quantity:i.quantity})),shippingAddress,coupon:couponApplied?'SAVE10':undefined,paymentMethod:f.get('paymentMethod')||'cod'});setCart([]);if(r.data.checkoutUrl)window.location.href=r.data.checkoutUrl;else{alert(`Order #${r.data.order._id.slice(-8)} placed successfully`);nav('/orders');loadOrders()}}catch(x){alert(x.response?.data?.message||'Checkout failed')}}
 const Header=()=> <><header><div className="brand" onClick={()=>nav('/')}>ShopNest</div><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products, brands and more"/></div><div className="actions"><button onClick={()=>user?nav('/orders'):setAuthOpen(true)}>👤 {user?.name||'Login'}</button><button onClick={()=>nav('/cart')}>🛒 Cart <b>{cart.reduce((s,i)=>s+i.quantity,0)}</b></button>{user?.role==='admin'&&<button onClick={()=>nav('/admin')}>⚙️ Admin</button>}</div></header><div className="promo">🚚 Free delivery on orders above ₹999 • Use <b>SAVE10</b> for 10% off</div></>;
 const Home=()=> <main><section className="hero"><div><p className="eyebrow">NEW SEASON • 2026</p><h1>Everything you need.<br/><em>Delivered simply.</em></h1><p>Discover everyday products with secure checkout, stock visibility, order tracking and easy returns.</p><button className="primary" onClick={()=>document.getElementById('catalog').scrollIntoView()}>Shop now →</button></div><div className="hero-card">⚡<strong>Today’s picks</strong><small>Up to 40% off</small></div></section><section id="catalog"><div className="section-head"><div><h2>Trending products</h2><p>Handpicked for you</p></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest</option><option value="rating">Top rated</option><option value="price_asc">Price: low to high</option><option value="price_desc">Price: high to low</option></select></div><div className="chips">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><div className="grid">{products.map(p=><article className="card" key={p._id}><div className="imgwrap"><img src={p.images?.[0]}/>{p.compareAtPrice&&<span>{Math.round((1-p.price/p.compareAtPrice)*100)}% OFF</span>}</div><div className="cardbody"><small>{p.brand} · {p.category}</small><h3>{p.title}</h3><div className="rating">★ {p.rating||'New'} <span>({p.reviewCount||0})</span></div><div className="price">{money(p.price)} <del>{money(p.compareAtPrice)}</del></div><p className={p.stock<5?'low':''}>{p.stock<5?`Only ${p.stock} left`:p.stock+' in stock'}</p><button className="add" disabled={!p.stock} onClick={()=>add(p)}>{p.stock?'Add to cart':'Out of stock'}</button></div></article>)}</div></section><section className="features"><div>🔒<b>Secure payments</b><span>Protected checkout</span></div><div>↩️<b>Easy returns</b><span>7-day return window</span></div><div>📦<b>Live order status</b><span>Track every order</span></div><div>💬<b>Support</b><span>Fast customer help</span></div></section></main>;
 const Cart=()=> <main><div className="pagehead"><h2>Your cart</h2><button onClick={()=>nav('/')}>← Continue shopping</button></div>{!cart.length?<div className="empty">Your cart is empty.<br/><button className="primary" onClick={()=>nav('/')}>Shop products</button></div>:<div className="cartlayout"><div>{cart.map(i=><div className="cartitem" key={i.product}><img src={i.image}/><div><h3>{i.title}</h3><b>{money(i.price)}</b><div className="qty"><button onClick={()=>setCart(c=>c.map(x=>x.product===i.product?{...x,quantity:Math.max(1,x.quantity-1)}:x))}>−</button><span>{i.quantity}</span><button onClick={()=>setCart(c=>c.map(x=>x.product===i.product?{...x,quantity:x.quantity+1}:x))}>+</button><button onClick={()=>setCart(c=>c.filter(x=>x.product!==i.product))}>Remove</button></div></div></div>)}</div><aside className="summary"><h3>Order summary</h3><p>Subtotal <b>{money(subtotal)}</b></p><div className="coupon"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code"/><button onClick={()=>coupon.trim().toUpperCase()==='SAVE10'?setCouponApplied(true):alert('Invalid coupon')}>Apply</button></div>{couponApplied&&<p className="saved">SAVE10 applied: −{money(discount)}</p>}<p>Shipping <b>{shipping?money(shipping):'FREE'}</b></p><hr/><h2>Total <b>{money(total)}</b></h2><button className="primary wide" onClick={()=>nav('/checkout')}>Proceed to checkout</button></aside></div>}</main>;
 const Checkout=()=> <main><div className="pagehead"><h2>Secure checkout</h2><span>🔒 Protected checkout</span></div><form className="checkout" onSubmit={checkout}><section><h3>Delivery address</h3><div className="formgrid"><input name="fullName" defaultValue={user?.name||''} placeholder="Full name" required/><input name="phone" placeholder="Phone number" required/><input name="addressLine" className="full" placeholder="Address" required/><input name="city" placeholder="City" required/><input name="state" placeholder="State" required/><input name="pincode" placeholder="PIN code" required/></div><h3>Payment</h3><label className="pay"><input type="radio" name="paymentMethod" value="cod" defaultChecked/> Cash on Delivery</label><label className="pay"><input type="radio" name="paymentMethod" value="stripe"/> Card / UPI via Stripe Checkout</label></section><aside className="summary"><h3>Review order</h3>{cart.map(i=><p key={i.product}>{i.title} × {i.quantity}<b>{money(i.price*i.quantity)}</b></p>)}<hr/><p>Subtotal <b>{money(subtotal)}</b></p><p>Discount <b>−{money(discount)}</b></p><p>Shipping <b>{shipping?money(shipping):'FREE'}</b></p><h2>Total <b>{money(total)}</b></h2><button className="primary wide">Place order</button></aside></form></main>;
 const Orders=()=>{useEffect(()=>{loadOrders()},[]);return <main><div className="pagehead"><h2>My orders</h2><button onClick={()=>nav('/')}>Shop more</button></div>{!orders.length?<div className="empty">No orders yet.</div>:orders.map(o=><div className="ordercard" key={o._id}><div><b>Order #{o._id.slice(-8)}</b><small>{new Date(o.createdAt).toLocaleString()}</small></div><span className="status">{o.status}</span><strong>{money(o.total)}</strong><div className="progress">{['placed','confirmed','shipped','delivered'].map(s=><i key={s} className={o.status===s||['confirmed','shipped','delivered'].indexOf(o.status)>['placed','confirmed','shipped','delivered'].indexOf(s)?'on':''}></i>)}</div></div>)}</main>};
 const Admin=()=>{const[adminOrders,setAdminOrders]=useState([]),[title,setTitle]=useState(''),[price,setPrice]=useState(''),[stock,setStock]=useState('');useEffect(()=>{api.get('/admin/orders').then(r=>setAdminOrders(r.data)).catch(()=>{})},[]);const create=async e=>{e.preventDefault();try{await api.post('/products',{title,price:Number(price),stock:Number(stock),category:'General',brand:'ShopNest',description:'Quality everyday product',images:['https://images.unsplash.com/photo-1523275335684-37898b6baf30']});alert('Product added');setTitle('');setPrice('');setStock('')}catch(x){alert(x.response?.data?.message||'Admin access required')}};return <main><div className="pagehead"><h2>Admin dashboard</h2><button onClick={()=>nav('/')}>Storefront</button></div><div className="admin"><form className="adminform" onSubmit={create}><h3>Add product</h3><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Product title" required/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Price" type="number" required/><input value={stock} onChange={e=>setStock(e.target.value)} placeholder="Stock" type="number" required/><button className="primary">Create product</button></form><section><h3>Recent orders</h3>{adminOrders.map(o=><div className="order" key={o._id}><b>#{o._id.slice(-8)}</b><span>{o.user?.email}</span><span>{money(o.total)}</span><select value={o.status} onChange={async e=>{await api.patch('/admin/orders/'+o._id+'/status',{status:e.target.value});setAdminOrders(a=>a.map(x=>x._id===o._id?{...x,status:e.target.value}:x))}}>{['placed','confirmed','shipped','delivered','cancelled'].map(s=><option key={s}>{s}</option>)}</select></div>)}</section></div></main>};
 let content=location.pathname==='/cart'?<Cart/>:location.pathname==='/checkout'?<Checkout/>:location.pathname==='/orders'?<Orders/>:location.pathname==='/admin'&&user?.role==='admin'?<Admin/>:<Home/>;
 return <div><Header/>{content}<footer>© 2026 ShopNest · Full-stack e-commerce application · React + Express + MongoDB</footer>{authOpen&&<div className="modal"><form onSubmit={authSubmit}><button type="button" className="close" onClick={()=>setAuthOpen(false)}>×</button><h2>{mode==='login'?'Welcome back':'Create account'}</h2>{mode==='register'&&<input name="name" placeholder="Full name" required/>}<input name="email" type="email" placeholder="Email" required/><input name="password" type="password" placeholder="Password" minLength="6" required/><button className="primary" disabled={loading}>{loading?'Please wait…':mode==='login'?'Login':'Register'}</button><p onClick={()=>setMode(mode==='login'?'register':'login')} className="switch">{mode==='login'?'New here? Create account':'Already have an account? Login'}</p></form></div>}</div>
}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
